id: P000666
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5664
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་
  author: ''
  volumes:
    c397969bc4ad4e18aa914a42aa14b394:
      image_group_id: I1KG5672
      title: ''
      volume_number: 1
      total_pages: 154
