id: P000666
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 16:35:59.764716
source_metadata:
  id: bdr:W1KG5664
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་
  author: ''
  volumes:
    c397969bc4ad4e18aa914a42aa14b394:
      image_group_id: I1KG5672
      title: ''
      volume_number: 1
      total_pages: 154
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
