id: IF9C4C746
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:36:02+00:00'
last_modified: '2022-06-07T12:35:29.210901+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5664
  title: བླ་མ་མཆོད་པའི་ཆོ་ག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C3D8:
      image_group_id: I1KG5672
      title: ''
      total_pages: 154
      order: 1
      base_file: C3D8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
